DROP FUNCTION IF EXISTS fun_add;

DELIMITER $$

CREATE FUNCTION fun_add (p_n1 DOUBLE,p_n2 DOUBLE)
RETURNS DOUBLE
DETERMINISTIC

BEGIN
		DECLARE v_res DOUBLE;
		SELECT IFNULL(p_n1,0)+IFNULL(p_n2,0) INTO v_res;
		RETURN v_res;
END ;
$$
DELIMITER ;
